CREATE TABLE IF NOT EXISTS team_members (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  team_id     INTEGER NOT NULL REFERENCES warehouse_teams(id) ON DELETE CASCADE,
  member_name TEXT NOT NULL
)
